AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Max: 150
  Enabled: true

Metrics/ParameterLists:
  Max: 6
  Enabled: true

Layout/LineLength:
  Max: 300
  Enabled: true

Metrics/BlockLength:
  Max: 70
  Enabled: true
