# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in codemonkey.gemspec
gemspec

gem "dotenv"
gem "pry-byebug"
gem "pry-rails"
gem "rake", "~> 13.0"
gem "rdoc"
gem "rubocop"

group :test do
  gem "rspec"
  gem "vcr"
  gem "webmock"
end
